apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-react-service.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    {{- include "test-react-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: frontend
    {{- include "test-react-service.selectorLabels" . | nindent 4 }}
